name: Deploy to EC2

on:
  push:
    branches:
      - main # or your branch

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          ssh-keyscan github.com >> ~/.ssh/known_hosts
            # Change to your project directory
            cd /home/ubuntu/MatchHood
                  git pull origin main

            # Build the frontend
            cd frontend
            npm install
            npm run build

            # Navigate to backend and install dependencies
            cd ../backend
            npm install

            # Restart backend with PM2
            pm2 restart backend  # Adjust process name if needed

          EOF
